// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: goods.proto

package cmd

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Sel2Pb_AddGoods_FullMethodName     = "/sel2pb.sel2pb/AddGoods"
	Sel2Pb_UpdateGoods_FullMethodName  = "/sel2pb.sel2pb/UpdateGoods"
	Sel2Pb_DelGoods_FullMethodName     = "/sel2pb.sel2pb/DelGoods"
	Sel2Pb_GetGoodsById_FullMethodName = "/sel2pb.sel2pb/GetGoodsById"
	Sel2Pb_SearchGoods_FullMethodName  = "/sel2pb.sel2pb/SearchGoods"
)

// Sel2PbClient is the client API for Sel2Pb service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Sel2PbClient interface {
	// -----------------------goods-----------------------
	AddGoods(ctx context.Context, in *AddGoodsReq, opts ...grpc.CallOption) (*AddGoodsResp, error)
	UpdateGoods(ctx context.Context, in *UpdateGoodsReq, opts ...grpc.CallOption) (*UpdateGoodsResp, error)
	DelGoods(ctx context.Context, in *DelGoodsReq, opts ...grpc.CallOption) (*DelGoodsResp, error)
	GetGoodsById(ctx context.Context, in *GetGoodsByIdReq, opts ...grpc.CallOption) (*GetGoodsByIdResp, error)
	SearchGoods(ctx context.Context, in *SearchGoodsReq, opts ...grpc.CallOption) (*SearchGoodsResp, error)
}

type sel2PbClient struct {
	cc grpc.ClientConnInterface
}

func NewSel2PbClient(cc grpc.ClientConnInterface) Sel2PbClient {
	return &sel2PbClient{cc}
}

func (c *sel2PbClient) AddGoods(ctx context.Context, in *AddGoodsReq, opts ...grpc.CallOption) (*AddGoodsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddGoodsResp)
	err := c.cc.Invoke(ctx, Sel2Pb_AddGoods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sel2PbClient) UpdateGoods(ctx context.Context, in *UpdateGoodsReq, opts ...grpc.CallOption) (*UpdateGoodsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGoodsResp)
	err := c.cc.Invoke(ctx, Sel2Pb_UpdateGoods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sel2PbClient) DelGoods(ctx context.Context, in *DelGoodsReq, opts ...grpc.CallOption) (*DelGoodsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelGoodsResp)
	err := c.cc.Invoke(ctx, Sel2Pb_DelGoods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sel2PbClient) GetGoodsById(ctx context.Context, in *GetGoodsByIdReq, opts ...grpc.CallOption) (*GetGoodsByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGoodsByIdResp)
	err := c.cc.Invoke(ctx, Sel2Pb_GetGoodsById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sel2PbClient) SearchGoods(ctx context.Context, in *SearchGoodsReq, opts ...grpc.CallOption) (*SearchGoodsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchGoodsResp)
	err := c.cc.Invoke(ctx, Sel2Pb_SearchGoods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Sel2PbServer is the server API for Sel2Pb service.
// All implementations must embed UnimplementedSel2PbServer
// for forward compatibility
type Sel2PbServer interface {
	// -----------------------goods-----------------------
	AddGoods(context.Context, *AddGoodsReq) (*AddGoodsResp, error)
	UpdateGoods(context.Context, *UpdateGoodsReq) (*UpdateGoodsResp, error)
	DelGoods(context.Context, *DelGoodsReq) (*DelGoodsResp, error)
	GetGoodsById(context.Context, *GetGoodsByIdReq) (*GetGoodsByIdResp, error)
	SearchGoods(context.Context, *SearchGoodsReq) (*SearchGoodsResp, error)
	mustEmbedUnimplementedSel2PbServer()
}

// UnimplementedSel2PbServer must be embedded to have forward compatible implementations.
type UnimplementedSel2PbServer struct {
}

func (UnimplementedSel2PbServer) AddGoods(context.Context, *AddGoodsReq) (*AddGoodsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGoods not implemented")
}
func (UnimplementedSel2PbServer) UpdateGoods(context.Context, *UpdateGoodsReq) (*UpdateGoodsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGoods not implemented")
}
func (UnimplementedSel2PbServer) DelGoods(context.Context, *DelGoodsReq) (*DelGoodsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelGoods not implemented")
}
func (UnimplementedSel2PbServer) GetGoodsById(context.Context, *GetGoodsByIdReq) (*GetGoodsByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoodsById not implemented")
}
func (UnimplementedSel2PbServer) SearchGoods(context.Context, *SearchGoodsReq) (*SearchGoodsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchGoods not implemented")
}
func (UnimplementedSel2PbServer) mustEmbedUnimplementedSel2PbServer() {}

// UnsafeSel2PbServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Sel2PbServer will
// result in compilation errors.
type UnsafeSel2PbServer interface {
	mustEmbedUnimplementedSel2PbServer()
}

func RegisterSel2PbServer(s grpc.ServiceRegistrar, srv Sel2PbServer) {
	s.RegisterService(&Sel2Pb_ServiceDesc, srv)
}

func _Sel2Pb_AddGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGoodsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Sel2PbServer).AddGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sel2Pb_AddGoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Sel2PbServer).AddGoods(ctx, req.(*AddGoodsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sel2Pb_UpdateGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGoodsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Sel2PbServer).UpdateGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sel2Pb_UpdateGoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Sel2PbServer).UpdateGoods(ctx, req.(*UpdateGoodsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sel2Pb_DelGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelGoodsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Sel2PbServer).DelGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sel2Pb_DelGoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Sel2PbServer).DelGoods(ctx, req.(*DelGoodsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sel2Pb_GetGoodsById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoodsByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Sel2PbServer).GetGoodsById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sel2Pb_GetGoodsById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Sel2PbServer).GetGoodsById(ctx, req.(*GetGoodsByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sel2Pb_SearchGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchGoodsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Sel2PbServer).SearchGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sel2Pb_SearchGoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Sel2PbServer).SearchGoods(ctx, req.(*SearchGoodsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Sel2Pb_ServiceDesc is the grpc.ServiceDesc for Sel2Pb service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sel2Pb_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sel2pb.sel2pb",
	HandlerType: (*Sel2PbServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddGoods",
			Handler:    _Sel2Pb_AddGoods_Handler,
		},
		{
			MethodName: "UpdateGoods",
			Handler:    _Sel2Pb_UpdateGoods_Handler,
		},
		{
			MethodName: "DelGoods",
			Handler:    _Sel2Pb_DelGoods_Handler,
		},
		{
			MethodName: "GetGoodsById",
			Handler:    _Sel2Pb_GetGoodsById_Handler,
		},
		{
			MethodName: "SearchGoods",
			Handler:    _Sel2Pb_SearchGoods_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goods.proto",
}
